apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
    - port: 80
      targetPort: 3116
      protocol: TCP
      name: http
