# .github/workflows/deploy.yml
name: Deploy
on: ['push']

jobs:
  deployment:
    permissions: write-all
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v1'
      - name: Set Test Kubeconfig
        run: |
          echo "KUBECONFIG_FILE<<EOF" >> $GITHUB_ENV
          echo "${{ vars.KUBECONFIG_FILE }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: 'Deploy'
        uses: 'glopezep/helm@v1.7.1'
        with:
          release: 'example-api'
          namespace: 'default'
          chart: '.helm/example/'
          token: '${{ github.token }}'
          values: |
            name: example-api
            namespace: default
            image: nittendev/example-api
