# .github/workflows/deploy.yml
name: Deploy
on: ['push']

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1

    - name: 'Deploy'
      uses: 'glopezep/helm@v1.7.1'
      with:
        release: 'example-api'
        namespace: 'default'
        chart: '.helm/example/'
        token: '${{ github.token }}'
        values: |
          name: foobar
        value-files: "values.yaml"
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'