name: Docker Image Deploy Kubernetes - Helm
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - uses: licenseware/helm@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }} # JSON/YAML encoded string
          action: upgrade -i # upgrade -i, install, uninstall, etc.
          atomic: "1"
          build-dependencies: "0" # helm dep build
          chart-dir: ./.helm
          chmod-kubeconfig: "1" # `chmod 600 kubeconfig-filepath`
          cleanup: "1" # delete all the files i.e. kubeconfig & values
          cleanup-on-fail: "1" # delete newly created resources on failure
          create-namespace: "0"
          helm-version: "v3.10.1" # https://github.com/helm/helm/releases
          namespace: default
          release-name: ${{ github.event.repository.name }}
          reuse-values: "0" # possible values: [0, 1] default: 0
          timeout: 10m
          update-dependencies: "1" # helm dep update
          values-string: name=example-api,namespace=default,image=nittendev/example-api
          wait: "1"