name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: nittendev/example-api
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ vars.DOCKER_PASSWORD }}